### ISSUE TITLE
Condensing methods

### ISSUE THREAD

**Issue by Rodrigap** [raychengy/jamming#2]
https://github.com/raychengy/jamming/blob/9c7eaf40585e7d10566c9d826f8d9a303bbaafba/src/components/App/App.js#L37-L41

I love how concise you are in each of your methods, but sometimes it's actually helpful to use a few extra lines. For example, I always prefer when the last step of a function is setting the state using a predefined variable; I think it's confusing and easier to make mistakes when you put unnecessary logic within your setState method. Here's how I would've written this:

  ```
removeTrack(track) {
    let tracks = this.state.playlist;
    tracks = tracks.filter(el => el.id !== track.id);

    this.setState({
      playlist: tracks
    });
  }
```

It's the same exact logic, but slightly rearranged and a little more clear!

**Comment by raychengy** [comment]
Makes sense. Changes were made. Thank you.
