### ISSUE TITLE
Grade: Exceeds Expectations

### ISSUE THREAD

**Issue by Rodrigap** [raychengy/jamming#4]
Really great job on this! It looks like you have a good handle on React, which is awesome. Each of your components is perfectly organized, and your methods are all concise and well-written. My biggest suggestions is to not get ahead of yourself in terms of condensing methods. I love that you're able to sort out the logic in your head this way, but sometimes it's more appropriate to define a couple of extra variables and use 2 or 3 lines instead of just one. This way, when others go into your code to collaborate, it's easier for them to see what's going on and to not mess up the existing codebase. Overall, I don't have any other big critiques about this! If you'd like an added challenge, consider picking some cool new features to add to this. You can take some of the feature suggestions from the feature request project and see if you can implement them!

**Comment by raychengy** [comment]
Thanks! 👍
